# Generated by Django 5.2.1 on 2025-05-23 13:56

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Userinfo",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=32)),
                ("password", models.CharField(max_length=64)),
            ],
        ),
    ]
